# How to run
# ansible-playbook 34-sync-cosmo-images.yml -e '{"cosmo_services": ["aria", "cosmo"]}'

- hosts: localhost
  roles:
    - common
    - aws
    - inventory

  tasks:
  - name: Open tunnel
    shell: "ssh -fNL 5001:localhost:30000 ubuntu@{{ groups['kube_minion'][0] }}"
    register: output

  - debug: var=output

  - name: tag and push
    docker_image:
      name: "{{ item }}:latest"
      force_tag: yes
      repository: "localhost:5001/cosmos/{{ item }}:latest"
      push: yes
      source: local
    with_items: "{{ cosmo_services }}"

  - name: remove images
    docker_image:
      repository: "localhost:5001/cosmos/{{ item }}"
      tag: latest
      state: absent
    with_items: "{{ cosmo_services }}"

  - name: kill tunnel
    shell: "pkill -f '{{ output.cmd }}'"
